### ISSUE TITLE
Multiple values in a cell and specify which value to use for sorting

### ISSUE THREAD

**Issue by nextofsearch** [schrodinger/fixed-data-table-2#144]
Hi,

If I have a table with multiple values in a cell, can I specify which value (i.e. hidden input) to use for sorting?

**Comment by wcjordan** [comment]
Hey there, since FDT doesn't encapsulate the data, you have the power to sort it however you like.  However you want to map a row id to a cell renderer's output will work.

If you look at the [SortExample](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/SortExample.js), you can implement any sort you want simply by changing the behavior of DataListWrapper's getObjectAt method.  Similarly you should build whatever sort you want into the data store from your project.

**Comment by nextofsearch** [comment]
@wcjordan 
Can you please check out [this image](http://i63.tinypic.com/24dpojn.png)? The cell has 2 values: one is an original value and the other is a variation compared to control group. The current implementation is done using jQuery dataTable and I am searching for an alternative since it is not compatible with React. The way I did with dataTables is adding a number using input tag as hidden and set sorting to be done with the input tag in the cell, not just any number.

**Comment by wcjordan** [comment]
Sure this is supported.  One of the fundamental principles of React (and this data table as well) is to split the view rendering and the data processing responsibilities.  As such FDT2 only deals with the view rendering responsibility.

Your task is to provide a mapping from a row index and column key to the content you want displayed in the cell at that position.  You do this by providing a React component as a [cell prop to each column](http://schrodinger.github.io/fixed-data-table-2/api-column.html).

I recommend you sort your data as you choose and then allow the React cell component to access that sorted data when it's rendered so the row index can do a lookup against your sorted data.
