### ISSUE TITLE
poor performance for table with 50 columns

### ISSUE THREAD

**Issue by mauvew** [schrodinger/fixed-data-table-2#146]
the performance is quite bad with around 50-100 columns, scroll vertically is very janky, anything we can do to improve it?

**Comment by wcjordan** [comment]
Hey @mauvew, most of the time we see issues like this it's because the individual cells haven't been optimized.  Do your cells include shouldComponentUpdate checks or use React.PureComponent?  If not, you should add that to optimize them.  This [guide](https://facebook.github.io/react/docs/optimizing-performance.html) can be very helpful.

Additionally you may want to play enable the [allowCellsRecycling](http://schrodinger.github.io/fixed-data-table-2/api-column.html) prop for your columns.  It will prevent too many DOM elements from being created when you have many columns.

If those don't work for you, I recommend reproducing the issue in a JsFiddle and posting here so we can take a look.  Here's an [example fiddle](https://jsfiddle.net/uq8osbp1/12/) which may help you get started.

Also we've recently introduced a pureRendering flag on columns which optimizes the checks to skip rendering even more.  It's experimental, but you can try it out.  There's some discussion here #138

**Comment by KamranAsif** [comment]
@mauvew were you able to get your performance concerns fixed? If not, please share a jsfiddle.

**Comment by mauvew** [comment]
@KamranAsif  sorry for the delay, company blocked jsfiddle so that i cannot have a look in time. what I found is in the fiddle, it works well with allowCellsRecycling marked as true, though it won't change the data in the current viewport when clicking "change data".
[fiddle](https://jsfiddle.net/uq8osbp1/24/)
will have a further look once back to company and comment here. thanks

**Comment by KamranAsif** [comment]
@mauvew You were incorrectly rendering your cell.
You rendered {this.state.value}, but failed to update state when props changed.

Here is an updated fiddle: https://jsfiddle.net/uq8osbp1/27/
I also included pureRendering={true} that should be a good boost to performance

**Comment by mauvew** [comment]
thanks for the help

Strangely, as in our application, vertical scroll is a bit janky while horizontal scroll is very smooth. In the fiddle, it is opposite. will have a further investigation next week. When i say scroll, i mean using the mouse to drag scrollbar to scroll

**Comment by mauvew** [comment]
Had a look today, noticed that if adjust the width, height and row height of the table to make it display nicely in a desktop screen. and also extend it to 1500 rows with 100 columns, it become very slow.
Here is the fiddle: [https://jsfiddle.net/uq8osbp1/28/](https://jsfiddle.net/uq8osbp1/28/)

**Comment by wcjordan** [comment]
The biggest issue here seems to be the example writing the whole data object into the DOM for each cell.  Removing that by using a spread operator to strip it before writing the cell gave me a huge speed up.
```
    const {data, ...propsWOData} = this.props;
    var value = this.props.data[this.props.rowIndex][this.props.columnKey];
    return <Cell {...propsWOData}>Cell: {value}</Cell>;
```

I was also able to improve things by upgrading to React 15.4.
I've done these changes in this fiddle here:
https://jsfiddle.net/pooh25g7/11/

I still see an issue where when horizontal scrolling we remount the cells instead of updating their props.  This causes an unnecessary re-render.  You can see this with the console.log('new props') message I added in the fiddle linked above.  I pinged @KamranAsif on discord who has dealt with similar problems before, and hopefully we can resolve it to get everything up to snuff.

**Comment by wcjordan** [comment]
Looking into the issue with re-mounting cells, it only happens for a new column when added.  I think things are fast enough without addressing that, especially if using the React production libraries.

Could you check out if applying any of these fixes helps with your case and let us know?

**Comment by mauvew** [comment]
thanks for all the help. vertical scroll did improve a lot while, as you mentioned, horizontal scroll is a bit slow. Especially when dragging the scroll bar to scroll.
