### ISSUE TITLE
Table with fixed columns, strange scroll behavior

### ISSUE THREAD

**Issue by jphamilton** [schrodinger/fixed-data-table-2#149]
I have a table with 4 fixed columns. My table is mostly filled with inputs. When I tab between the inputs, only the current row is scrolled. At this point, it is impossible to tell what is going on because the row is not aligned with the column header any longer.

I would expect all the visible rows to scroll and not just the current row. I attempted a workaround using the onFocus event of my inputs and scrollToColumn, but no matter what I do, scrollToColumn doesn't seem to work for me (even when I straight up hard code values into the prop, nothing).

![roll-scroll-issue](https://cloud.githubusercontent.com/assets/19796/25010684/798af496-2030-11e7-80f6-a4cdb94cb461.png)

**Comment by wcjordan** [comment]
Welp that's definitely not good.  Would it be possible for you to put together a JSFiddle which reproduces the issue?  You can use [this as a template](https://jsfiddle.net/gww7j03L/) to get you started.

**Comment by jphamilton** [comment]
[Here ya go](https://jsfiddle.net/y27o89s6/1/)

Just start tabbing and you will see it.

**Comment by wcjordan** [comment]
Thanks, definitely reproducible.  This is a bit tricky to fix because we're wrestling with the browsers native behavior for tabbing between inputs since we don't use native scrolling.  

Here's my suggested fix.  @KamranAsif what are your thoughts? and how much do you think we should build into FDT vs provide an example for?

1. Capture any tab on an input bubbling up to the FDT component and prevent default on it.
2. Query to get all tab-able inputs in grid (see Know which elements are tab-able [here](http://stackoverflow.com/a/10730308)).
3. Sort by tab order (tabIndex, position in DOM).
4. Find the next element following event.target.
5. Determine the row & column for that element and scroll to said row & column using scrollToColumn & scrollToRow functionality.
6. Focus the next element.

All in all this seems pretty risky to me and may take a bit to get right.  @jphamilton do you have any interest in trying this out in user space for your specific use case and letting us know how it goes?  Steps 2 & 3 can particularly be scoped down if only dealing with a single use case.  I can help with any steps which are unclear, particularly if you have issues with FDT & step 5.

**Comment by jphamilton** [comment]
I'll try this out, but for some reason (that I cannot reproduce in the JSFiddle), scrollToColumn is not working for me. I've hard-coded a column outside of my initial viewport...and nothing. But I will keep you posted.

**Comment by jphamilton** [comment]
[Ok, here is my work around](https://jsfiddle.net/y27o89s6/4/), which I think is fairly simple (although this JSFiddle is quite janky).

Tabbing works. So does tabbing to the next row. Shift+Tab to go backwards seems to work as well.

**Comment by wcjordan** [comment]
Hey @jphamilton did you close this because your issue is resolved?  If so glad to hear, I'll carve out some longer term tickets for trying to provide better library support once I get a chance to sync with @KamranAsif .

I noticed on your fiddle there are still issues with scrollToColumn.  Did you get those worked out for your application?

**Comment by jphamilton** [comment]
@wcjordan What issues did you see? With Chrome latest the fiddle was working perfectly for me. In my app, not so much (but this is my fault bc my table takes too long to re-render and it interferes with the tabbing). I closed because it seems like this (or something similar) is a viable workaround.

**Comment by wcjordan** [comment]
I was able to still reproduce the issue, but only when the grid is in a very small window (3 columns fit on screen).  It looks good at larger sizes.  I thought this may have been the scrollToColumn issue you mentioned.

Either way if you feel good about the approach, I'll carve out follow ups for internal support in the future and we can close.  Let me know if you run into any additional problems.

**Comment by wcjordan** [comment]
Filed #152 to track this in the future.

**Comment by priyesh1984** [comment]
Hi,

I am not able to use up and down keys to scroll.

**Comment by tkirda** [comment]
What worked for me is updating CSS on `.fixedDataTableRowLayout_main` from `overflow: hidden` to `overflow: clip`, which forbids all native scrolling on the container. At the same time scrolling to column via
