### ISSUE TITLE
Which approach to simple export of generated HTML/DOM by fixed-data-table-2

### ISSUE THREAD

**Issue by fabm22** [schrodinger/fixed-data-table-2#156]
## Expected Behavior 

Sorry if misplaced place to ask, but using some given filtered (or not) state state/representation of data displayed in a fixed-data-table-2, what would be the easier way to have the ability to export the produced HTML/DOM representing the visual table into some Excel file ?

I can't find an existing example or path to a solution in issues and on the web.

## Possible Solution

An alternative I came across would, I guess, require accessing a synthetic representation of the generated HTML by FixedDataTable then, using jQuery([codepen link](https://codepen.io/kostas-krevatas/pen/mJyBwp)), and exporting this Html to an excel file. 
Is there an easy way to do this ? 
Am I better making a little custom converter js function "parsing" the generated DOM by FixedDataTable and essentially doing the same than this previous link does ?

Thanks a lot for your help !

**Comment by wcjordan** [comment]
Hey @fabm22, FDT doesn't currently have any functionality to help export to Excel.  At Schrodinger we've implemented a copy to Excel functionality, but rather than doing it through FDT, we've used the source data for the grid, and iterated it generating a CSV of the values we expect the grid to render.

If you need to actually generate an Excel file it's a bit more difficult but something like [js-xlsx](https://github.com/SheetJS/js-xlsx) may help.

I'm going to close as I don't think this is FDT related, but feel free to ping me with follow-up questions.
