### ISSUE TITLE
Some basic how-to examples would be helpful

### ISSUE THREAD

**Issue by glenne** [schrodinger/fixed-data-table-2#168]
The README.md for the repo implies that all that is needed is a quick npm install and a simple index.js.  The exmples pages have beautiful examples including a link for the example code.

However, the code in the README.md generates errors.  The nice examples appear to require some extra boilerplate around the example which doesn't appear to be in the repo or explained.  

As a new person to node.js and react I find the barrier very high to trying out fixed-data-table-2.

For example, using the README.md example produces this error:
`./src/index.js
  Line 28:  'MyCustomCell' is not defined  react/jsx-no-undef`

Removing use of MyCustomCell results in this error: 
`_registerComponent(...): Target container is not a DOM element.`

My suggestion would be 

- update the README.md with a complete simple example that a noob can follow and be successful.
- include the css reference in the example instead of saying 'import it into any module'.  What module would that be?    How do I do that?
- For the example pages, provide a how-to for how to use one of the examples.  As a newbie, I'd like to start from one of these and edit it to display my data.  How do you get the area to scroll, have margins, have a side menu etc.

I'd love to submit a pull request to fix these but it's beyond my abilities at this point.

**Comment by wcjordan** [comment]
Unfortunately, React & modern JS have require a transpilation step to work.  So there's no way to provide an .html + .js example which works out of the box while still encouraging best practices for syntax.

In an ideal world, we could create a new repo which uses [create-react-app](https://github.com/facebookincubator/create-react-app) and some JSX & HTML to put together a minimal example.  I've spun out a ticket for that with #170, but it's more work than I'm able to dedicate to this at this time.

In the meantime, I'll update the basic example to say it's demonstrates how FDT usage should look and point the reader to the examples for working examples.

To help you, I'd be interested to know more regarding what you've tried with the examples and where you're seeing issues.  For example it looks like you're using eslint since "is not defined react/jsx-no-undef" is an eslint error.  

"_registerComponent(...): Target container is not a DOM element." indicates to me that you don't have a div with the id example in your HTML.  You may want to look at the APIs for [getElementById](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) and [ReactDOM.render](https://facebook.github.io/react/docs/react-dom.html#render) to understand how they work, as we assume some familiarity in our docs.

Wrt to CSS, I recommend linking the stylesheet from your HTML file with
```
<link href="dist/fixed-data-table.css" rel="stylesheet">
```
I'll update the docs to encourage this alongside using CSS modules.  If you want to know more about CSS modules, there's plenty of reading material such as [this article](https://glenmaddern.com/articles/css-modules), but I don't think it's as widely used an approach as React is yet.  So may be a more advanced concept for a later day.

You should be able to run the examples with `npm run site-dev-server`
And to help follow them as a complete example, I recommend looking at these files:
https://github.com/schrodinger/fixed-data-table-2/blob/master/site/examples/ExamplesPage.js
https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/helpers/cells.js
https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/helpers/FakeObjectDataListStore.js
https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/ObjectDataExample.js

Note that these are run through a webpack transpilation using babel though, so it may introduce new challenges to understanding.  When in doubt, I recommend trying to build up from [react-create-act](https://github.com/facebookincubator/create-react-app#getting-started) towards using React components as they have dedicated many more resources towards documenting getting started with a React app from scratch than we have.

**Comment by wcjordan** [comment]
I've updated the docs to address the easy stuff with #171.  You can see the results here: https://github.com/wcjordan/fixed-data-table-2

Let me know your thoughts.  I'll leave the harder work to be picked up when someone gets to #170

**Comment by glenne** [comment]
As a new react user I find a recipe works best for me.  After some learnings, I found this sequence of commands created a nice demo page.  Adding the require for the css so it comes from the module install made it show up nicely formatted.

1. npm install -g create-react-app
2. create-react-app my-app
3. cd my-app/
4. yarn add fixed-data-table-2

5. Replace src/index.js with
`import ReactDOM from 'react-dom';`
`require('fixed-data-table-2/dist/fixed-data-table.css');`
`//  paste Create Reusable Code README.md example code here`
`ReactDOM.render(<MyTable />, document.getElementById('root'));`

6. yarn start

**Comment by wcjordan** [comment]
Cool, were you able to get that going?  If so and you'd like to create a repo demonstrating the usage, that would be a good step towards #170

**Comment by wcjordan** [comment]
Closed via #171, I'll let #170 cover the half of this around an example repo
