### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jonashartwig** [schrodinger/fixed-data-table-2#190]
Performance with 30 columns is poor. (50 rows)

## Expected Behavior
Hiding a column should have immediate updates without noticeable lags.

## Current Behavior
Removing a column takes 1.5seconds for react to do magic.

Also scrolling is laggy.

My question mostly is if that is expected? It works fine as soon as i go down to less than 10 columns.
## Context
It makes the user experience bad

## Your Environment
* Version used: 0.7.17
* Browser Name and version: chrome latest
* Operating System and version (desktop or mobile): osx
* webpack 2.6 with babel 6

regards

**Comment by mritterhoff** [comment]
@jonashartwig Do you have `allowCellsRecycling` set to `true` on your Columns? Should help with performance. [Definition](https://github.com/schrodinger/fixed-data-table-2/blob/45275492ca196b46f66baf254f7f2591e6850ae4/src/FixedDataTableColumn.js#L172) and [an example](https://github.com/schrodinger/fixed-data-table-2/blob/b05aa441bf036541c5a1791f54443474e9d3083d/examples/ReorderExample.js#L93).

**Comment by jonashartwig** [comment]
I added this to <Column /> it dit not improve the performance. Scrolling and removing columns is still laggy.

**Comment by wcjordan** [comment]
Hey @jonashartwig, most of the time we hear this it's caused by cells which haven't implemented shouldComponentUpdate.  Could you double check all your cells do that.  The [React optimization guide](https://facebook.github.io/react/docs/optimizing-performance.html) can be very helpful for this.

If that doesn't work there are some more steps you could take detailed in [this comment](https://github.com/schrodinger/fixed-data-table-2/issues/146#issuecomment-293570322).  If those don't work for you, I recommend reproducing the issue in a JsFiddle and posting here so we can take a look. Here's an [example fiddle](https://jsfiddle.net/uq8osbp1/12/) which may help you get started.

**Comment by jonashartwig** [comment]
ok. will do and report back.

**Comment by jonashartwig** [comment]
So I looked into the issue. I forgot to set pureRendering and allowCellsRecycling. I implemented a proper shouldComponentUpdate on Cell level. This did not improve performance at all. So I investigated further and I found the issue in how I used Immutablejs. I used toJS() function which always creates new properties if the column visibility changed (even for the data). So I created a proper wrapper which made column re-rendering way less expensive. It went from 1000 cell re-renders down to 100 from that column removed/added. It also majorly improved header cell dragging performance. However there is still a major noticeable delay when i remove a column completely even when the other columns did not change. I wanted to implement a Wrapper around Column which I was not allowed to do from the api. Any suggestions how I get a shouldComponentUpdate into the Column? I am right now not sure If this is required anyways. I don't know if the render method is called on Column. The columnKey and key on Column properties do not change. However on each re-render I have to create a new function for the column header cell for the click event to bind the correct data: this._handleColumnSort.bind(null, mapping) I dont really know if that could be the issue.

Thanks for the help so far. Any other suggestions?

Regards

**Comment by wcjordan** [comment]
That's funny, it sounds like immutable JS did the opposite of what it's designed for.  Anyway, it sounds like what you're doing is a bit more complicated than what I've seen before.  Is it possible for you to create a JsFiddle which demonstrates the reproduction?

I don't think adding shouldComponentUpdate to a column will do anything since it's not a rendered component (it's just used as a data object).  If you want to try though, there's discussion about how to override column in #175.

Your binding of _handleColumnSort does sound like it will break the shouldComponentUpdate for the column header cell.  See [this article](https://daveceddia.com/avoid-bind-when-passing-props/) on why it's an issue.  I also like these benchling articles which discuss the bind issue among other gotchas:
http://benchling.engineering/deep-dive-react-perf-debugging/
http://benchling.engineering/performance-engineering-with-react/

**Comment by jonashartwig** [comment]
I will look into your recommendations and come back. Immutable js does however work as expected if you do not transform the immutable objects to plain json objects :)

regards

**Comment by jonashartwig** [comment]
So I think We can close this issue. We had a production release yesterday and the performance had a major increase compared to the development build. I think according to all the hints I improved it as much as I could. Thanks again!

**Comment by ardok** [comment]
Just wondering, has anyone ever tried rendering with 2 fixed columns, and 52 scrollable columns (in total 54 columns), with 20 rows?

The horizontal scrolling seems to be laggy for me.
I set `allowCellsRecycling` for everything.
I also tried to implement shouldComponentUpdate for each cell, but it's still laggy.

If you're wondering why would I need 52 columns, it's something that has to do with weekly metric.

**Comment by ardok** [comment]
Oh @wcjordan nvm then, I checked out that fiddle you have in #146 , and the scrolling there is indeed a bit "laggy".
I just thought that it was only my table, but it looks like it is the expected performance.

What I meant by "laggy" is that (I'm on Mac), if I just scroll with one full motion (and fast), it will not be smooth. It will skip some columns and "jump".

**Comment by wcjordan** [comment]
I recommend reading the whole thread, particularly be sure you're looking at [this fiddle](https://jsfiddle.net/pooh25g7/11/) from [this comment](https://github.com/schrodinger/fixed-data-table-2/issues/146#issuecomment-295060175).  Other fiddles may have issues.

I believe that one shows immediate renders and is fast.  But not sure if you're looking for something else with smooth.

**Comment by ardok** [comment]
Attached is a gif.
When the table is scrolling, I just did it with one swing motion, by fully utilizing the momentum scrolling, and you can see how it quite skips some columns instead of smooth scrolling.

BUT if I scroll little by little, slowly, then it's smooth. It's just when I do the "momentum" scrolling, that it's laggy.

I don't know whether it's just my laptop or actually it's different from you.

![aug-15-2017 13-53-56](https://user-images.githubusercontent.com/1380581/29335994-5555c4b4-81c1-11e7-8434-6fc3e9f971ba.gif)

**Comment by wcjordan** [comment]
interesting.  I'm on my linux machine atm, but I'll check it out on my mac later.

It might be related to #154 as well which is specific to mac track pads and magic mice.

**Comment by wcjordan** [comment]
I am able to reproduce the issue from that fiddle on my mac, but not able to reproduce it on this [reorder example](http://schrodinger.github.io/fixed-data-table-2/example-reorder.html).  Can you confirm that's the case for you as well?

I'll look into adding more columns and see if that causes an issue with the example.  If so #153 might fix the issue once it gets in.  If not I'll look at bit more at what the examples rendering and see if I can tell why it's a pain.

**Comment by ardok** [comment]
I think it's due to the reorder example not having that many columns.
So yes, I don't see the problem on that reorder example.

**Comment by ardok** [comment]
Something to add, Firefox on Mac has the worst performance for the scrolling for that fiddle: https://jsfiddle.net/pooh25g7/11/

But, not really a problem for me because my users are only using latest Chrome browser.

**Comment by wcjordan** [comment]
If I add a 50 columns to the reorder example, I'm able to see some slowness in Firefox when running with React's dev library, but not with the production library or in Chrome with either build of React.

My recommendation is to profile what rendering takes place during a horizontal scroll in your app.  If you're seeing any cells or headers being rendered that's a good case to dig in further on.  

Beyond that #153 should help with this once it's released, but I don't have a timeline for it at the moment.
