### ISSUE TITLE
Testing FDT2

### ISSUE THREAD

**Issue by leafoflegend** [schrodinger/fixed-data-table-2#191]
Looking at the `src` code in this repo, it looks as though this codebase is entirely untested. Am I wrong? I mean, if so, a suggestion is to write tests. But, I am here more to ask a question openly to whoevers out there using this about if you've tested it, and if so what that looks like. I have some amount of testing on my variant, but it seems extremely difficult to replicate the behavior of the table in a test environment.

Columns don't seem to begin to attempt to render cells in any sort of test environment. That would be useful for testing the behavior of the table as a whole.

Less a bug than a general question to a large audience on if someone can supply an example with thorough testing of the table. Specifically, testing the callback function of the `cell` prop on a column. As, that is where quite a bit of logic can end up.

**Comment by miskreant** [comment]
Our tests aren't very extensive at the moment, but you should be able to run them locally via `npm test` and also [view them on Travis](https://travis-ci.org/schrodinger/fixed-data-table-2). We appreciate your suggestions, and have it in our pipeline to improve on and add more tests in the future. We would also be happy to welcome any improvements or new tests. If you would like to contribute, feel free to submit a PR for us to review. Thanks!

**Comment by wcjordan** [comment]
@leafoflegend to follow up on @miskreant's response, Facebook didn't open source their tests yet for the repo.  If you want to add your voice to the [issue here](https://github.com/facebook/fixed-data-table/issues/130), it'd be appreciated.

We do have many integration level tests for our usage at Schrodinger on LiveDesign, but they run with Selenium and are full stack rather than unit tests.  

For unit tests we have the mocha tests mentioned above, but they only really exist on the v0.8-beta branch and mostly focus on state management.  It would be great to add something for renderers, maybe with Jest snapshot testing or something similar.

Do you have a reproduction of the issue with rendering cells?  Are you doing it with something like Jest snapshot testing or an Enzyme shallow renderer?  One thing that stands out as weird, is you mention getting columns to render cells, but columns aren't rendered components (they're just used for table configuration and not passed to React).  Maybe there's something related to the weirdness of that API we can help you work out if you could put up a repo for reproducing what you're seeing.

**Comment by leafoflegend** [comment]
@wcjordan I ended up getting Jest snapshots to work - a thing to mention on my end is I am definitely abusing the table at this point. Cells filled with interactive components, material-ui, general tomfoolery. The issue I'm having now is listening in to events on the cells themselves. They don't seem to register in any sort of `enzyme` simulate event. But I'm still going at that. Yeah, I've looked at the source code there as that was an early problem of mine was inability to create custom columns - because columns never actually render. Its definitely an issue in terms of attempting to test the `<Column />`.

**Comment by wcjordan** [comment]
Interesting.  It could be because the cells are only used as a template and the actual rendered element is a [cloned element](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableCell.js#L283).  I don't know the details of the React & Enzyme interactions for that, but it may be a start to your research.

I'm going to close for now as I don't see anything actionable, but feel free to follow up if you have a toy repo for reproducing and we can help investigate further.
