### ISSUE TITLE
Don't fire onClick when double clicked but onDoubleClick

### ISSUE THREAD

**Issue by binarykitchen** [schrodinger/fixed-data-table-2#199]
Looks like your latest version does trigger the onClick callback when a row is double clicked which is IMO wrong. Should call only onDoubleClick instead.

**Comment by wcjordan** [comment]
To my knowledge our onClick & onDoubleClick props are passed directly to the div element, so I recommend trying to reproduce the issue you're seeing outside of FDT and filing against React.

Going to close as I don't plan to break behavior from React

**Comment by quixotically** [comment]
@binarykitchen A click event will fire no matter what before a double click event. Since both the onClick and onDoubleClick handlers are passed directly to the element as @wcjordan said, I would recommend to either:

1) Make your click handler compatible with your double click event handler
2) Do something like setting a timeout before firing the click handler in case a double click event occurs https://css-tricks.com/snippets/javascript/bind-different-events-to-click-and-double-click/
