### ISSUE TITLE
React 16 - Component returning an array of Columns

### ISSUE THREAD

**Issue by BorisTB** [schrodinger/fixed-data-table-2#241]
I have a component Columns that is returning an array of FixedDataTableColumns and I'm getting this error: `Error: Invariant Violation: child type should be <FixedDataTableColumn /> or <FixedDataTableColumnGroup />`

I'm using it like this:
```
<Table
        { ...props }
        rowsCount={ filteredData.length }
        scrollToColumn={ props.scrollToColumn }
      >
        <Columns
          data={ filteredData }
          columnsConfigs={ props.columns }
        />
</Table>
```

## Expected Behavior
Component is returning a proper columns so I guess it should be working ok.

## Current Behavior
Error: `Error: Invariant Violation: child type should be <FixedDataTableColumn /> or <FixedDataTableColumnGroup />`

## Possible Solution
Validate components returned from the Columns component, do not validate the Columns component

## Steps to Reproduce (for bugs)
Create a component returning array of FixedDataTableColumns and use it in the Table

## Context
I can't keep nice and clean code, when i have to generate columns in the same component where I use Table it just looks messy.

## Your Environment
"fixed-data-table-2": "^0.8.1",
"react": "^16.0.0",
"react-dom": "^16.0.0",

**Comment by wcjordan** [comment]
This comes from the [restrictive validation](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L982) we have on what Children components can be passed to a table.  I'm going to close as won't fix since that validation provides value.

Instead you should change you Columns component into a method which returns an array of columns and call it with any args you need to pass to props like so:

```
<Table
        { ...props }
        rowsCount={ filteredData.length }
        scrollToColumn={ props.scrollToColumn }
      >
        { getColumns(filteredData, columnsConfigs) }
</Table>
```
