### ISSUE TITLE
Expanding last row doesn't trigger scroll render

### ISSUE THREAD

**Issue by Laete** [schrodinger/fixed-data-table-2#290]
The problem can be easily shown here: https://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html.
Scroll the page to the bottom and try to expand the last row. It expands, but you can see the expanded row only after you scroll UP, not DOWN.
And if there is no scroll before you expand, the only way to see the expanded part is resizing the window.

### Expected Behavior
After I expand the row, the table recounts its height and shows/hides scrollbar if necessary

### Current Behavior
After I expand the last row, the table doesn't recount and the expanded part is not visible.

### Possible Solution
Trigger rerender of the grid after expanding the last line or trigger scrolling up.

### Steps to Reproduce (for bugs)
1. draw grid with expandable rows
2. expand the last row

### Your Environment
* Version used: 0.8.8
* Browser Name and version: any
* Operating System and version (desktop or mobile): desktop

**Comment by wcjordan** [comment]
Yep, I can reproduce this.  I'll take a look and see if I can fix.  Thanks for filing

**Comment by Laete** [comment]
Thnx, really looking forward to this fix.

**Comment by wcjordan** [comment]
@Laete this is an unfortunate issue with the existing architecture and isn't an easy fix.

Luckily it has been fixed in the v1.0-beta release.  If you use the version 1.0.0-beta.4 from npm it should fix this issue.
Please reach out if you have any issues with that or the beta version in general.

Note we're still working on some perf improvements and docs for the beta version so I recommend pinning to a specific beta until we go stable.

**Comment by Laete** [comment]
@wcjordan, thank you, beta-version fixed the problem. I'll notify you if we get any issues.
