### ISSUE TITLE
Highlighting rows and current row index when scrolling

### ISSUE THREAD

**Issue by npavlovic** [schrodinger/fixed-data-table-2#303]
Hi there,

I want to have one table with date ranges that should be like navigation table and the other where all the data is.

So what I wanted to do is when I scroll trough data table, the date range that I'm scrolling trough is highlighted in the other table.

I'm facing two issues here:

- I'm unable to get table row to get highlighted. I've tried to make use of rowClassNameGetter like you did in scrollToRow example but had no luck with that.

- Also I would like to know how can I have current row index value when scrolling trough data table?
i.e. how can I pass the info about rows that are currently in table focus to other component.

There is also a third problem with scrollToRow which just gets row barley to focus. But I see you already have that issue opened.

Can you help me with some of this? Thanks.

**Comment by wcjordan** [comment]
I'm not sure I can help w/ the first issue, beyond to say it's worth debugging if the class name is getting added to the row div.  If not, check whether your getter is returning the class name you expect.

For the second issue you can register an onScrollEnd handler which will be called with 3 args: x scroll position, y scroll position, and the first row index.  From the first row index, you'll have to write your own logic to determine the other rows though using row heights and the table size.

I'm going to close for now since this isn't a library issue, but let me know if you have additional questions as you work through the task.
