### ISSUE TITLE
Should FixedDataTable* components extend React.PureComponent?

### ISSUE THREAD

**Issue by CharlesStover** [schrodinger/fixed-data-table-2#324]
I see the components are primarily extending `React.Component`. Is there a reason they don't extend `React.PureComponent`? I'm finding that they are re-rendering very extensively. Maybe not often individually, but the fact that there are _so many_ cells in a tabular view, that is a _lot_ of re-renders. It seems like this problem would fix itself if they simply extended `React.PureComponent` instead of `React.Component`. Is there a reason they are `React.Component`?

**Comment by wcjordan** [comment]
Good question, but unfortunately that would cause issues.  Since cell renderers work off of data which is often not contained in the React component tree, using a PureComponent would result in changes to that data not causing re-renderers.  We do highly recommend using PureComponent for any cell renderers, which has been enough for us to support 60 fps on grids of 10k rows and 100 columns with complex cells.

If you're having performance issues I recommend perusing these threads:
#146 #190 #307 

There is a rough discussion of passing data through the component tree which can be found on #166 and https://github.com/schrodinger/fixed-data-table-2/pull/162#issuecomment-305547043 if you'd like to contribute.

I'm going to close this but feel free to continue the discussion if you have questions.
