### ISSUE TITLE
how to create multiped  head columns group?

### ISSUE THREAD

**Issue by NexxLuo** [schrodinger/fixed-data-table-2#329]
create columns group ,like this:

let columns=[{
  title: 'Company',
  children: [{
    title: 'Company Address',
    dataIndex: 'companyAddress',
    key: 'companyAddress',
 children: [{
      title: 'Street',
      dataIndex: 'street',
      key: 'street',
      width: 200,
    }, {
      title: 'Block',
      children: [{
        title: 'Building',
        dataIndex: 'building',
        key: 'building',
        width: 100,
      }]
  }, {
    title: 'Company Name',
    dataIndex: 'companyName',
    key: 'companyName',
  }],
}, {
  title: 'Gender',
  dataIndex: 'gender',
  key: 'gender',
  width: 60,
  fixed: 'right',
}]
 

how to do it?
I find that many people want this function, but i can`t find an example that can be run.
thanks

**Comment by wcjordan** [comment]
It looks like you've deleted the issue template :(
Unfortunately, there's not much I can do to help you with this level of detail.  You may want to check out the [column groups example](http://schrodinger.github.io/fixed-data-table-2/example-column-groups.html), which seems a little like what you're asking for.

**Comment by NexxLuo** [comment]
i mean the column group,not scroll.
but now fixed-data-table-2 can create simple column group,just one level,  why can not create complex column group?

**Comment by wcjordan** [comment]
I don't think I have the answer you're looking for, but I can point you to the related code if you'd like to try for yourself:

[FixedDataTableColumnGroup.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableColumnGroup.js) has the group definition.
Rendering the groupHeader happens here in [FixedDataTable.js' render method](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L626)
[_populateColumnsAndColumnData](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L1020) handles updating and setting up the columns.
[FixedDataTableWidthHelper.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTableWidthHelper.js) and this [block in _calculateState](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L1204) handles the flex width prop.

**Comment by singharpit94** [comment]
Currently ColumnGroup Component only accepts Columns as children , instead of that if we can make the ColumnGroup Class efficient enough to handle complex cases such as ColumnGroup Component can also be passed inside ColumnGroup, will that be the right direction to achieve this behavior. If yes are you willing to accept a PR for the same.

**Comment by wcjordan** [comment]
I'd accept a PR for this if it proved simple and looked easy to maintain.

I think an alternative approach might be to permit passing a component in for the whole header which could allow users of the library to have much more flexibility with how the header is rendered (at the cost of having them write and maintain that custom header).

**Comment by singharpit94** [comment]
Thanks for the alternative approach. One more question I had is there any reason of not exposing FixedDataTableRow component for end users. Lets say my custom header component may require use of FixedDataTableRow component. Is it fine to expose it from FixedDataTable? @wcjordan

**Comment by wcjordan** [comment]
I'd recommend using it as inspiration rather than re-using it.  It has a few major responsibilities: styling, handling user interaction / clicks, and rendering cell groups.
My assumption is the styling and user interaction handlers are simple enough they could be rewritten and probably simplified for the header case.  The rendering of cell groups is probably opinionated enough that you'd want to rewrite that to support your flexible header component.

One idea might be to try copying the FixedDataTableRow and try reconstructing the rendering behavior without the cell groups.  Also potentially simplifying styling and handlers.  Since you don't need the cell recycling functionality of the cell groups, I think it will be cleaner (but I'm not certain).
