### ISSUE TITLE
Get position of row relative to table top/bottom

### ISSUE THREAD

**Issue by SimonChris** [schrodinger/fixed-data-table-2#331]
I am a using a custom select dropdown in my table, and have already dealt with the 'overflow-hidden' problem by using React portals.

However, I need my dropdown to open downwards if it is at the top part of of the table, but upwards if it is at the bottom. I can control the open direction programmatically, but I can't figure out how to check if my row is at the top or bottom of the table. 

rowIndex doesn't seem to account for visibility if the table content has been scrolled, so that doesn't work. If I could somehow check the index of the row among the currently visible rows, then that would be sufficient, but there doesn't seem to be any way of doing that.

**Comment by pradeepnschrodinger** [comment]
Closing this, since with the [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) release, `onScrollEnd` has a fourth param -- `endRowIndex` -- which can be used to get the range of visible rows, which should solve the issue.

Feel free to continue the discussion if you need more help.
