### ISSUE TITLE
expanded row Height remains fixed

### ISSUE THREAD

**Issue by rajatrawataku1** [schrodinger/fixed-data-table-2#337]
I am using expanded row FDT, but inside the row content I have another table whose height is somewhat around 300px but the rows height does not changes according to the content. Is there any way to implement this?

@wcjordan  please help ?

Thanks in advance

**Comment by wcjordan** [comment]
I would investigate the subRowHeightGetter and rowExpanded props.  See the [Expanded Rows example](http://schrodinger.github.io/fixed-data-table-2/example-expanded-rows.html) ([source](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/ExpandedExample.js)).

I'm going to close since this isn't an issue, but I'll try to answer any follow ups best I can.
