### ISSUE TITLE
Columns not updating

### ISSUE THREAD

**Issue by lakshmiaswath** [schrodinger/fixed-data-table-2#345]
## Expected Behavior
After updating the state the columns should be updated.

## Current Behavior
Columns are not getting updated

[table.txt](https://github.com/schrodinger/fixed-data-table-2/files/2331694/table.txt)
Above  is attached the component which uses Table, Column from fixed-data-table-2.
It uses JobCell and TechCell ad customized <cell> components.
[jobcell.txt](https://github.com/schrodinger/fixed-data-table-2/files/2331697/jobcell.txt)
[techcell.txt](https://github.com/schrodinger/fixed-data-table-2/files/2331698/techcell.txt)

Can you please tell why is that when ever the state is updated the cells aren't updated ? 
Where am i going wrong?

**Comment by wcjordan** [comment]
Hey there.  I'm afraid there isn't enough detail here for me to assist you.  I recommend checking out the [examples page](http://schrodinger.github.io/fixed-data-table-2/example-object-data.html) or creating a CodePen which demonstrates your issues.

I'm closing since this doesn't appear to be a bug, but please feel free to respond if you have questions about the specifics of my suggestions.  Good luck
