### ISSUE TITLE
Set { passive: false } explicitly when registering 'wheel' event handler

### ISSUE THREAD

**Issue by xinghul** [schrodinger/fixed-data-table-2#351]
This introduces **no changes** to `fixed-data-table-2` itself, because by default, when you register event listener, it's `passive: false` by default.

But in order for us to use passive event listeners in React, we need to override default `addEventListener` before React's `dispatchEvent` kicks in. (Here's the status of React passive event listener support FYI: https://github.com/facebook/react/issues/6436)

One way of doing that is using something like `default-passive-events` (https://github.com/zzarcon/default-passive-events), which basically makes `passive: true` by default when you registering event listeners.

And it will break `fixed-data-table-2`, since you cannot preventDefault in passive event handler, line 104:
<img width="607" alt="screen shot 2018-09-26 at 6 27 39 pm" src="https://user-images.githubusercontent.com/6555861/46118140-f185fa00-c1b9-11e8-8f28-7a05a48222e1.png">

**Comment by wcjordan** [comment]
I'd consider a PR for this.  I'm not in love with the idea of working around react by replacing system globals, but since FDT doesn't need to do that, just to explicitly pass the object, I'll look at this.

One thing to keep in mind is I'll need to verify this continues to work on all versions of React.  Please be sure in creating a PR to provide a way for me to test that and ensure this won't disrupt any library users.

Thanks!

**Comment by pradeepnschrodinger** [comment]
Closing the issue since [v1.0.0](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0) release uses passive scroll listeners..
