### ISSUE TITLE
Scrolling left in a table is broken in any example on Chrome v 51

### ISSUE THREAD

**Issue by albertolacework** [schrodinger/fixed-data-table-2#36]
## Expected Behavior
If you scroll right on the table you should be able to scroll left after any other action.

## Current Behavior
It varies but usually it doesn't work. I can consistently get it to scroll if I scroll up or down first and then try left.

## Possible Solution
Update to Chrome v52.

## Steps to Reproduce (for bugs)
Open Any Example.
Reduce window size or increase some column widths.
Scroll right.
Switch tabs to something else and then come back.
Attempt to scroll the table left.
???

## Context
Scrolling left is very important.

## Your Environment
* Version used: The Example
* Browser Name and version: Chrome v51
* Operating System and version (desktop or mobile): Mac OS X El Capitan V10.11.5
* Link to your project: Mine does as well but so does the example so you can see it there

**Comment by wcjordan** [comment]
I'm having some trouble reproducing this.  I'm using Chrome v51 and Mac OS X Yosemite.
I've included a screenshare of scroll left working on [youtube here](https://youtu.be/ryeBW0YZNzU)

Do you have any console errors which indicate an issue?  Do you get the impression that the issue is related to a JS exception or performance issue?  Also could you try disabling any chrome plugins and see if this is still reproducible (incognito can be handy for this).  Also are you using an external mouse or the trackpad when you see the issue?

You may want to set a breakpoint in _onScroll of [FixedDataTable.js](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js#L1114) and see if you can identify the cause.

**Comment by KamranAsif** [comment]
I can't repo this either. @albertolacework can you record a screencast of this bug?

**Comment by albertolacework** [comment]
Update: I upgraded to Chrome v52 and can no long reproduce this issue. I supposed I'll close it then.
