### ISSUE TITLE
DoubleClick event listener on column resizer knob

### ISSUE THREAD

**Issue by singharpit94** [schrodinger/fixed-data-table-2#381]
Add double click event listener on column resizer knob

## Expected Behavior
Double click/click event listener should get triggered on column resizer knob

## Current Behavior
Adding doubleClick/click event listener does not work on column resizer knob

## Context
I tried adding onDoubleClick event listener on column resizer knob in [FixedDataTableCell](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableCell.js#L243)
but it is never getting triggered. I tried with normal container divs after muting onColumnResize callback and it was working fine.

I tried debugging the cause and it seems we are adding mouse events on document.body in [DOMMouseTracker](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/vendor_upstream/dom/DOMMouseMoveTracker.js) and this seems to cause the issue.I tried by not adding these events on document.body and all my listeners started working although the functionality was broken for column resize.

I would like to add a double click listener on column resizer knob so that I can perform certain operations only on double click. Any leads or suggestion why this is not working and what I can do to get this working.

**Comment by wcjordan** [comment]
Could you provide a CodePen or other example which reproduces this?

**Comment by pradeepnschrodinger** [comment]
When you perform a simple click on column resizer knob, _onColumnResizerMouseDown is called, which in turn leads to rendering of FixedDataTableColumnResizeHandle (with updated columnResizingData).

Now, FixedDataTableColumnResizeHandle is rendered at the same place as your mouse cursor, and since it's an absolutely positioned element with high z-index, your mouse-up event would be used on this component. 
Double click requires both mouse down and mouse up to be on the same component.
This is probably the issue.

I don't think the DOMMouseTracker should be an issue, as it just listens on the document level.

@singharpit94 One thing you could try is, adding this line `style['pointer-events'] = 'none'`
just [before the render](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableColumnResizeHandle.js#L126).

@wcjordan This shouldn't be a problem as the component doesn't have any mouse handlers attached. What do you think?

**Comment by wcjordan** [comment]
That works for me
