### ISSUE TITLE
Feature Request: Group Rows

### ISSUE THREAD

**Issue by KevinYaoooooo** [schrodinger/fixed-data-table-2#394]
Hey, your library is really cool, really help us to solve the large data rendering problem.

But, I see there is not so much support on Group Rows（like screenshot below, there is a group, when you expend it, the rows belongs to that group expended）?

Actually, I try to continue display some columns and cells by using subRow, but I see there is no support on this, if I nested these directly with out performance consideration, it will turn out to be a bad UX and laggy.
 
So, do you have the plan to support this solution? 
![image](https://user-images.githubusercontent.com/12027816/52553437-721e5d80-2e1e-11e9-9c80-597a080d6db5.png)

**Comment by wcjordan** [comment]
There's currently 2 ways to do this.  The first is the way you've mentioned by embedding a table in the subrow.  You mention some performance concerns.  If you have a live example which demonstrates them, I can make some suggestions.  Checking your cells are pure components and walking through the [React Perf guide|https://reactjs.org/docs/optimizing-performance.html] can be helpful in those situations.

The other option is to map your nested rows into the table, but render the cells in their row in a styled way to indicate they're nested.  A nested table might be flattened in this way:

- 1 -> row 1
 - a -> row 2
 - b -> row 3
- 2 -> row 4
 - a -> row 5
 - b -> row 6
- 3 -> row 7

Since both those ways of supporting this exist and I'd like to keep this library minimal, I won't accept a PR to make this first class functionality.  I would be interested in adding examples that demonstrates how to do this though.
