### ISSUE TITLE
Need to pass scroll events to children in expandable grid

### ISSUE THREAD

**Issue by DaveCole** [schrodinger/fixed-data-table-2#395]
I have a `<Table>` component nested within another `<Table>` component, which is displayed in an expanded row (fixed-data-table-2 inception!) -- both scroll independently of one another, but I was wondering if there was a way to easily pass scroll events or scroll offset on the parent fixed-data-table-2 component to its children.  Thanks!

**Comment by wcjordan** [comment]
Hmm, I've never seen anyone try that.  Your best bet is probably to investigate [ReactWheelHandler|https://github.com/schrodinger/fixed-data-table-2/blob/master/src/vendor_upstream/dom/ReactWheelHandler.js] and how it's used in [FixedDataTable.js|https://github.com/schrodinger/fixed-data-table-2/blob/master/src/FixedDataTable.js].

I'm going to close for now since this isn't an issue or enhancement on our roadmap, but feel free to continue to ask questions if you need any clarification on the code base.

**Comment by DaveCole** [comment]
thanks @wcjordan sorry for posting the non-issue - I'll post back if I find a good solution.

**Comment by wcjordan** [comment]
No problem.  I don't have any concerns with folks posting non-issues on the repo.  It's easier for me to keep a history of discussions here than in the discord.

**Comment by DaveCole** [comment]
Hmm, I chipped away at it a little bit; setting stopScrollPropagation to false scrolls both together (desired behavior for me) when you're hovering over the nested Table but not when moused out (makes sense).  I just need to find a way to pass any scroll events to child divs when not moused over...

**Comment by wcjordan** [comment]
One option may be adding a listener to onHorizontalScroll on the tables and setting the other tables scroll position via scrollTop.

**Comment by DaveCole** [comment]
That did it @wcjordan !  I set the state of the container to hold the scroll offset from onHorizontalScroll and pass it in as a scrollLeft prop to the child grids and it worked like a charm.  The only drawback is it introduced a little bit of lag due to all the setState() calls.  Thanks for your help.
