### ISSUE TITLE
Scroll performance bug in beta?

### ISSUE THREAD

**Issue by maxjvh** [schrodinger/fixed-data-table-2#399]
## Expected Behavior / Current Behavior
`FixedDataTableCellGroup.shouldComponentUpdate` returns `true` if `nextProps.isScrolling` is falsy. from what i understand, this `isScrolling` prop is passed down from `FixedDataTable._renderRows`, where it is received from the `scrollbarsVisible()` function. looking at the `scrollbarsVisible` function, i can't see that it is ever returning a value with the key `scrolling`, which would mean that the value used in `_renderRows` is always `undefined` and thus `FixedDataTableCellGroup.shouldComponentUpdate` always returns true. is this an oversight or am i missing something here?

## Possible Solution
i'm not sure of a solution since i'm not quite sure how all of this logic is supposed to work.

## Context
this might be a reason why every row and cell is getting re-rendered on every scroll "tick", resulting in the performance of the beta branch being much worse than the latest stable version.

## Your Environment

* Version used: commit 3a93c509a7f83694994f55a37655201f745fd1dd
* Browser Name and version: Chrome 72
* Operating System and version (desktop or mobile): MacOS

**Comment by pradeepnschrodinger** [comment]
Hey, thanks for looking into this. 

This might be a long post.
The hierarchy  (if I'm not mistaken) is,
* FixedDataTableContainer ->
* FixedDataTable ->
* FixedDataTable._renderRows ->
* FixedDataTableBufferedRow ->
* FixedDataTableRow ->FixedDataTableRowImpl
* FixedDataTableCellGroup

------------------
> `FixedDataTableCellGroup.shouldComponentUpdate` returns `true` if `nextProps.isScrolling` is falsy. from what i understand, this `isScrolling` prop is passed down from `FixedDataTable._renderRows`, where it is received from the `scrollbarsVisible()` function. looking at the `scrollbarsVisible` function, i can't see that it is ever returning a value with the key `scrolling`,

The container gets `scrolling` from the redux store, and the [scroll start](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/reducers/index.js#L161) and [scroll end](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/reducers/index.js#L146) actions change it.
Not sure if the state is being changed elsewhere.

------------------
Earlier we used a private member `this._isScrolling` in FixedDataTable.js to keep track of scrolling and avoided scroll start and scroll end actions. This was removed through #385, and relies on redux to completely determine the scroll state. But the disadvantage is that a render can happen just because of this one action call. Thus the table can be rendered without any change in row indexes or scroll values, but scrolling being set to 'true'.

If we go by the master approach (using private member) and avoid the scroll start/stop action calls, this reduces extra function calls to the reducer (possibly extra renders too). This seems to improve performance, but again, still not as close to master branch's fluidity. 

If you're interested, could you branch out from just before #385 was commited and remove the scroll action calls found [here](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1050) and [here](stopScroll)? This should avoid the extra unnecessary Redux store updates when compared to master.

Then you could look into `FixedDataTableCellGroup` and maybe figure out how scrolling is being handled in `shouldComponentUpdate`. Btw, FixedDataTableCell [also uses](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTableCell.js#L94) `isScrolling`.

**Comment by pradeepnschrodinger** [comment]
> this might be a reason why every row and cell is getting re-rendered on every scroll "tick", resulting in the performance of the beta branch being much worse than the latest stable version.

@bodyflex, quick question, doesn't this occur in Master branch too? Or is it less?

One reason why scrolling is (again) less heavy computing in master, is due to how buffered rows outside of viewport remain unchanged even on large scrolls. Basically, while the user is scrolling, only the rows in the current viewport are updated, because the rest of the scrolls aren't visible anyway. And when scrolling is stopped, all the rows are updated. This is NOT done in beta as far as I know. 

@wcjordan Do you think we should open up an issue for tracking this feature?

**Comment by wcjordan** [comment]
Yes, that makes sense.  We may want to carve out tickets for all the potential perf enhancements you've found and tag them all with a tag (say beta-perf)

**Comment by bodyflex** [comment]
> @bodyflex, quick question, doesn't this occur in Master branch too? Or is it less?

it's much less, at least judging by the React profiler. i can share some screenshots later when getting back to testing this.

> The container gets scrolling from the redux store, and the scroll start and scroll end actions change it.

good to know! i completely missed that redux is being used.

> If you're interested, could you branch out from just before #385 was commited and remove the scroll action calls found here and here? This should avoid the extra unnecessary Redux store updates when compared to master.

i'll try this!

**Comment by bodyflex** [comment]
@pradeepnschrodinger @wcjordan below are screenshots of the performance of a scroll of roughly the same distance. i know they aren't useful for debugging, but they do demonstrate the problem pretty clearly.

latest stable release:
![screenshot 2019-03-06 at 14 18 15](https://user-images.githubusercontent.com/7894563/53881294-fded6900-401b-11e9-8d8a-7ec8353d5ff5.png)

latest commit in the beta branch:
![screenshot 2019-03-06 at 14 18 24](https://user-images.githubusercontent.com/7894563/53881300-004fc300-401c-11e9-8191-8876c7638cf6.png)

i tried branching out before #385 and removing the redux action dispatching like @pradeepnschrodinger suggested, but this didn't have a noticeable effect on performance just yet. i'll continue to dig into what `FixedDataTableCellGroup` is doing now.

**Comment by pradeepnschrodinger** [comment]
@bodyflex, @wcjordan, whoa! I didn't expect that much. Thanks for the screenshots.

> i tried branching out before #385 and removing the redux action dispatching like @pradeepnschrodinger suggested, but this didn't have a noticeable effect on performance just yet. i'll continue to dig into what `FixedDataTableCellGroup` is doing now. at least i can already tell that `props.isScrolling` is always false.

You'll also have to use `this._isScrolling` instead of `props.scrolling`. Otherwise every child in render will be using props.scrolling (which is never set and hence always falsey). Could you capture another screenshot for beta after using `this._isScrolling` ?

Btw, which tools are you using for this?

**Comment by pradeepnschrodinger** [comment]
> ## Expected Behavior / Current Behavior
> `FixedDataTableCellGroup.shouldComponentUpdate` returns `true` if `nextProps.isScrolling` is falsy. from what i understand, this `isScrolling` prop is passed down from `FixedDataTable._renderRows`, where it is received from the `scrollbarsVisible()` function. looking at the `scrollbarsVisible` function, i can't see that it is ever returning a value with the key `scrolling`, which would mean that the value used in `_renderRows` is always `undefined` and thus `FixedDataTableCellGroup.shouldComponentUpdate` always returns true. is this an oversight or am i missing something here?

@bodyflex, hey, I was completely wrong about this. You're right. It's wrongly taking the scrolling prop from the scroll selector. In fact, the correct way would be to just use this.props.scrolling.
This [mistake](( (https://github.com/schrodinger/fixed-data-table-2/pull/385/files#diff-293ddd101833c33e0069803f5068f2f7R828)) was added as part of #385 by me.

I'm pretty sure fixing it saves a lot of renders.

Try pulling out the latest beta ([v1.0.0-beta.12](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.12)), and then changing lines (starts at [line 821](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L821))
```js
 _renderRows = (/*number*/ offsetTop, fixedCellTemplates, fixedRightCellTemplates, scrollableCellTemplates,
    bodyHeight) /*object*/ => {
    const { scrollEnabledY, scrolling } = scrollbarsVisible(this.props);  // <- wrong !
    const props = this.props;
    return (
      <FixedDataTableBufferedRows
        isScrolling={scrolling}
        fixedColumns={fixedCellTemplates}
```
into
```js
 _renderRows = (/*number*/ offsetTop, fixedCellTemplates, fixedRightCellTemplates, scrollableCellTemplates,
    bodyHeight) /*object*/ => {
    const { scrollEnabledY } = scrollbarsVisible(this.props);  // <-- change
    const props = this.props;
    return (
      <FixedDataTableBufferedRows
        isScrolling={props.scrolling} // <-- change
        fixedColumns={fixedCellTemplates}
```
@bodyflex, can you try these changes? And we'll see what else makes up the unnecessary calls/updates. Feel free to make a PR for this too.

@wcjordan, there's still a few more performance optimizations that can be done. I'm adding the 'beta-performance' label to these types of issues/requests as you had suggested.

**Comment by bodyflex** [comment]
@pradeepnschrodinger thanks, tried that and indeed now the value of `isScrolling` seems to be `false` instead of `undefined`, which is already a bit better! however, the value is never `true` when scrolling by dragging the scrollbar (while scrolling is controlled). so there's no improvement in performance yet.

> Btw, which tools are you using for this?

if you mean the profiling tool, that's just the default profiler in Chrome viewing the "User timing" section which the dev build of React utilizes.

**Comment by pradeepnschrodinger** [comment]
> @pradeepnschrodinger thanks, tried that and indeed now the value of `isScrolling` seems to be `false` instead of `undefined`, which is already a bit better! however, the value is never `true` when scrolling by dragging the scrollbar (while scrolling is controlled). so there's no improvement in performance yet.
> 
> > Btw, which tools are you using for this?

That's strange... I expect [`this._onVerticalScroll`](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1013) to be called, which in turn calls [`this._didScrollStart`](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1026) and this would [set the scrollling state to true via a redux action dispatch](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1050). Further renders should use the scrolling prop (which will be on while scrolling)...

Aren't these calls being made? (make sure you're using the newest version which doesn't use `this._isScrolling`)

> if you mean the profiling tool, that's just the default profiler in Chrome viewing the "User timing" section which the dev build of React utilizes.

Aha, cool, thanks!

**Comment by bodyflex** [comment]
@pradeepnschrodinger sorry for the delay! `_didScrollStart` does get called when starting to scroll with the mouse wheel, but not when dragging the scroll bar. but even with the mouse wheel it never reaches the `scrollActions.startScroll()` call because the function returns before that since `props.scrolling` is false. why is this check necessary?

**Comment by pradeepnschrodinger** [comment]
@bodyflex,
> @pradeepnschrodinger but even with the mouse wheel it never reaches the `scrollActions.startScroll()` call because the function returns before that since `props.scrolling` is false. why is this check necessary?

Do you mean this [check](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1046
)? I reckon it's used to avoid unnecessary scroll starts. If the scrolling is already on, then there's no reason to start another scroll right?

If you mean these checks ([1](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L954), [2](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L999), [3](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1026)), it has a similar intent 
If scrolling is stopped, only then do we want to call _didScrollStart and start the actual scroll.

@wcjordan, thinking about these checks, wouldn't we just need one check at _didScrollStart? All the checks that call this function should be unnecessary. 

> @pradeepnschrodinger sorry for the delay! `_didScrollStart` does get called when starting to scroll with the mouse wheel, but not when dragging the scroll bar.

No worries! We're glad to get your help on this. Thank you for the follow ups!

Also, as per my understanding, _didScrollStart should get called while dragging the scroll bar (which would then set the scrolling state to true) . The code flow should be
[_onVerticalScroll](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1013) -> [_didScrollStart](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1036) -> [scrollActions.startScroll](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1050)

**Comment by bodyflex** [comment]
@pradeepnschrodinger yeah [this is the check](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1046) i was talking about

**Comment by pradeepnschrodinger** [comment]
@bodyflex, we just released [v1.0.0-beta.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.13) which has certain optimizations while scrolling.

Please let me know if you're still seeing performance drops in the latest beta release.

**Comment by bodyflex** [comment]
@pradeepnschrodinger there doesn't seem to be an improvement yet unfortunately :( it's still rendering all table cells completely on every scroll tick.

**Comment by bodyflex** [comment]
i should mention though that we are considering moving from controlled scroll (basically using body-scroll) to using the default scroll behaviour of this library. in the latter case the performance is good.

**Comment by pradeepnschrodinger** [comment]
> @pradeepnschrodinger there doesn't seem to be an improvement yet unfortunately :( it's still rendering all table cells completely on every scroll tick.

@bodyflex, that's really strange... This is the behavior that was fixed through  [v1.0.0-beta.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.13), so that only new cells within the view-port are rendered. And I just verified it works for me... Just to be sure, are you sure you're not using the older one (or something with additional commits on it)?

**Comment by bodyflex** [comment]
tried it again to make sure.

here's the performance of a short scroll action with `0.8.20`:
![Screenshot 2019-04-03 at 10 51 14](https://user-images.githubusercontent.com/7894563/55462003-80a71b00-55fe-11e9-9116-d5ad425339bc.png)

and here a similar action with `1.0.0-beta.13` installed freshly from npm:
![Screenshot 2019-04-03 at 10 55 24](https://user-images.githubusercontent.com/7894563/55462271-03c87100-55ff-11e9-99e3-70f5c2cbfce5.png)

are you sure that `yarn run build-npm` was ran before publishing? and did you test it with controlled scrolling? i.e. setting `scrollTop` from outside and not using the internal scroll bars or wheel scrolling.

**Comment by pradeepnschrodinger** [comment]
> i should mention though that we are considering moving from controlled scroll (basically using body-scroll) to using the default scroll behaviour of this library. in the latter case the performance is good.

> did you test it with controlled scrolling? i.e. setting `scrollTop` from outside and not using the internal scroll bars or wheel scrolling.

@bodyflex, aha! You nailed the coffin to this bug finding adventure! (hopefully this is really the root issue you're seeing, I'll check soon) !

Currently, in beta, controlled scrolling doesn't trigger a change scroll state. This was a known change which I added back with #392, which made sure that the scroll handlers are being called correctly, without redundancy.

But the PR came with the not so obvious bug (now pretty obvious lol) at line [577](https://github.com/schrodinger/fixed-data-table-2/pull/392/files#diff-293ddd101833c33e0069803f5068f2f7L577) where scrollStart and scrollEnd was avoided because it didn't make sense to start and stop the scroll state immediately. And even if it made sense, doing it here might trigger a new render just for an additional redux store change.

So in beta, since you are doing a controlled scroll (via an external scroll bar component?), the scroll state is never set to true.

The correct way is to set the scrolling state to true even for the controlled scrolls (known as jump scrolls in the reducer). I'll make a quick PR, wait for @wcjordan to approve, and cut a release.

**Comment by bodyflex** [comment]
> So in beta, since you are doing a controlled scroll (via an external scroll bar component?), the scroll state is never set to true.
yeah we are faking the height of `document.body` and using the native scroll bar of body :)

but cool, let's hope that fix fixes the issue for good!

**Comment by pradeepnschrodinger** [comment]
> yeah we are faking the height of `document.body` and using the native scroll bar of body :)

That's very interesting. Can I know why you guys took the approach? 
@wcjordan, I think you had something like this planned in the future?

> but cool, let's hope that fix fixes the issue for good!

I just released [v1.0.0-beta.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.15). Hopefully, this fixes controlled scrolling.

**Comment by bodyflex** [comment]
> That's very interesting. Can I know why you guys took the approach?

one of our views is completely based on the table so it made sense to use global scrolling for also scrolling the contents of the table. more importantly, we also have some toolbars above table which we want to scroll away when the user is scrolling down.

recently the situation has changed a bit though as we've removed some toolbars so we are considering moving back to the internal scroll logic of fixed-data-table-2. using global scroll has required some pretty ugly and complex hacks (including monkey patching the wheel handlers of fixed-data-table-2) which would be really nice to get rid of.

> I just released v1.0.0-beta.15. Hopefully, this fixes controlled scrolling.

the performance might be slightly better with this one, but not really close to what it is in 0.8.x. the render tree during scroll events still looks quite big though...

**Comment by wcjordan** [comment]
The approach of using a large DOM element to show the browser scrollbar is used by react-virtualized.  I mentioned we might want to explore integrating that as a potential scroll solution, but no other plans.

**Comment by pradeepnschrodinger** [comment]
> the performance might be slightly better with this one, but not really close to what it is in 0.8.x. the render tree during scroll events still looks quite big though...

@bodyflex, this is not what I'm seeing here... I tried controlled scrolling and performance seems great. I even kept track of the render counts for the components and they seem to be identical. In fact, beta has better render timings than the master branch.

We'll really need a detailed reproduction via codepen or a github repo / branch. Can you post one when you get the time? That'll be really crucial to solving your use case.

And btw, thanks for all the continued help! You really helped us find these issues and I think we're almost close to solving everything.

**Comment by bodyflex** [comment]
> We'll really need a detailed reproduction via codepen or a github repo / branch. Can you post one when you get the time? That'll be really crucial to solving your use case.

i was afraid it would come down to this 😅 our use-case is very complex and we've built quite a lot of stuff on top of fixed-data-table-2, but i'll see what i can do.

> And btw, thanks for all the continued help! You really helped us find these issues and I think we're almost close to solving everything.

thank you for being so responsive! this is one of the most positive open-source experiences i've had.
