### ISSUE TITLE
Horizontal scrolling is buggy on mobile

### ISSUE THREAD

**Issue by JoelSanchez** [schrodinger/fixed-data-table-2#456]
## Expected Behavior
On mobile devices, the user should be able to scroll horizontally within the table.

## Current Behavior
The table only scrolls forwards, never backwards, and even then, it's quite laggy.

## Steps to Reproduce (for bugs)
Use Chrome's device emulator here http://schrodinger.github.io/fixed-data-table-2/example-object-data.html

## Context
Our users aren't able to scroll the table horizontally on mobile devices.

## Your Environment
Any environment can be used, I think, since the examples are behaving exactly as in our application.

**Comment by pradeepnschrodinger** [comment]
Very strange...

First of all the table shouldn't even be scrollable by touch since the `touchScrollEnabled` table prop is not set in the [Object Data Example](http://schrodinger.github.io/fixed-data-table-2/example-object-data.html).

@JoelSanchez, can you try with the prop on? You'll get the correct scrolling behavior (seen in http://ld-desis.dev.bb.schrodinger.com:8090/example-touch-scroll.html) which shouldn't have any lag issues nor the can't go left issue.

**Comment by JoelSanchez** [comment]
Yes, that works. Thank you, somehow I missed that.

**Comment by pradeepnschrodinger** [comment]
Great! Feel free to reopen if you have troubles with that.

@wcjordan , we should probably fix this because the table can be touch scrolled even with `touchScrollEnabled` not set
