### ISSUE TITLE
Get list of visible rows?

### ISSUE THREAD

**Issue by jk171505** [schrodinger/fixed-data-table-2#467]
Is there a way to get a list of rows that are available in DOM or visible in the viewport?
I'm aware of firstRowIndex available in onScrollEnd method, but how can I get the exact range of rows (or rowIndexes) that are currently displayed?

**Comment by pradeepnschrodinger** [comment]
I don't think the current API in FDT gives information for the last row... 
You could try adding your row sizes until it goes beyond the table size (easier for uniformly sized rows),

@wcjordan, should we update the [scroll handlers](https://github.com/schrodinger/fixed-data-table-2/blob/v1.0-beta/src/FixedDataTable.js#L1119) so that endRowIndex is also passed? I don't think it will be a breaking change since we just have to add the last argument, and this does seem helpful, especially for multiple row sizes. This also seems like something FDT should have given as part of the API in first place?

**Comment by wcjordan** [comment]
I'm not opposed to it.  @jk171505 could you submit a PR for that?

**Comment by pradeepnschrodinger** [comment]
@jk171505, apologies for the delays. 
Last row index will be provided for `onScrollStart` and `onScrollEnd` from [v1.0.0-beta.22](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.22) onwards.

> Provide index of last row in view port to the scroll callbacks (#469) (Fixes #467)
> 
> onScrollStart and onScrollEnd now has a fourth param, which is the index of the last row in the view port

Closing this, but feel free to continue the conversation if you run into any issues.
