### ISSUE TITLE
Touch scrolling on Android triggers page refresh

### ISSUE THREAD

**Issue by Pakaa** [schrodinger/fixed-data-table-2#471]
## Expected Behavior
Scrolling upward should hide the elements on the bottom of the table while revealing elements on the top of the table

## Current Behavior
Scrolling upward refreshes the page

## Possible Solution
I think this one and the many other scrolling issues have to do with the passive event listener configurations, but I know that adding 'overscroll-behavior: none' to the document body does not fix it

## Steps to Reproduce (for bugs)
Have a scrollable table
Scroll down
Scroll back up

## Context
You can only scroll in one direction

## Your Environment
* Version used: 
* Browser Name and version: Chrome 75.0.3770.101
* Operating System and version (desktop or mobile): Android Oreo

**Comment by pradeepnschrodinger** [comment]
@Pakaa , hey there,
Are you using the beta version? A lot of bug fixes and features are added into the v1.0-beta branch, which is our current active branch of development. Could you try it out and see if the issue still exists?

Also could you try using the `stopScrollDefaultHandling` prop turned on, since I suspect the issue here is related to #154 or #419.

And also make sure for touch devices, you have the prop `touchScrollEnabled` turned on (see #456).

**Comment by Pakaa** [comment]
Hello!  I plugged in some beta versions and found that while beta 21 was unusable, beta 20 did fix this particular issue while I had the stopScrollDefaultHandling prop.  There are other bugs in the beta but it sounds like you guys already caught this one.  I'll close this ticket and wait for the next release.  Thanks @pradeepnschrodinger

**Comment by pradeepnschrodinger** [comment]
> Hello! I plugged in some beta versions and found that while beta 21 was unusable, beta 20 did fix this particular issue while I had the stopScrollDefaultHandling prop.

Glad it solved the issue :)

Could you give more info about why beta 21 is unusable? And is it in anyway related to [this recent issue](https://github.com/schrodinger/fixed-data-table-2/pull/460#issuecomment-506913766)? This will help a lot in reproducing and fixing it.
