### ISSUE TITLE
I want to know how fixed-data-table-2 concretely implements the lazy loading of table data

### ISSUE THREAD

**Issue by liangzhuang327** [schrodinger/fixed-data-table-2#474]
I want to know how fixed-data-table-2 concretely implements the lazy loading of table data

**Comment by wcjordan** [comment]
This is probably a good starting point:
https://docs.google.com/document/d/1y0yulUDnqYmMctMUxcx49pppwdqZAYe9cKpJHL8Tc7I/edit

The implementation is changed for the v1 beta branch, but we haven't documented how that works yet, so your best bet would be to read the code.

I'm going to close this since it's not an issue, but feel free to respond here if you have further questions.
