### ISSUE TITLE
Remove use of create-react-class?

### ISSUE THREAD

**Issue by daveisfera** [schrodinger/fixed-data-table-2#479]
`create-react-class` is stated as officially supported in the documentaiton, but [appears to no longer be supported](https://github.com/facebook/react/issues/16515#issuecomment-523080306). The code could be removed by migrating everything to classes.

## Expected Behavior
`create-react-class` is no longer used

## Current Behavior
It's installed in `node_modules` and relies on code that is no longer maintained.

## Possible Solution
Move everything to classes and possible use `React.PureComponent` if setting React 15.3 as the minimum version is an acceptable solution. I can submit a PR, if this is ok.

## Context
Increases size of install and pulls in unmaintained dependencies

## Your Environment
* Version used: 0.8.26
* Browser Name and version: Chrome 76.0.3809.132
* Operating System and version (desktop or mobile): Mac OS 10.14.6

**Comment by pradeepnschrodinger** [comment]
@daveisfera, we have a beta branch ([v1.0.0-beta](https://github.com/schrodinger/fixed-data-table-2/tree/v1.0-beta)) which is almost ready for release. This is also the current target for development and improvements.

From a quick glance, It seems like `v1.0.0-beta` already migrated usages of create-react-class to `React.Component`. 
If that's not the case everywhere, then a PR would be nice. 

Having pure components seems like a good idea, but we have to be extra careful since some of the components aren't exactly pure (like `FixedDataTableBufferedRows`), and might break if made a `React.PureComponent`.

Btw, why is setting React 15.3 as the minimum a requirement? Is it because that was the earliest release where the extends syntax worked, or `React.PureComponent` was introduced?

**Comment by daveisfera** [comment]
I just checked and there aren't any uses of `create-react-class` in that branch, so that should be good. Is there an ETA for when 1.0 will be released?

And yes, the comment about React 15.3 was just in regards to that being [when `React.PureComponent` was added](https://github.com/facebook/react/blob/master/CHANGELOG.md#1530-july-29-2016).

**Comment by pradeepnschrodinger** [comment]
> I just checked and there aren't any uses of `create-react-class` in that branch, so that should be good. Is there an ETA for when 1.0 will be released?

Great, thanks. I would expect 1.0 to be released in a month or two (🤞). We're already in the process of preparing for the release.

I'll marking this issue as closed, but feel free to continue the discussion.
