### ISSUE TITLE
ScrollContentHeight does not get updated when a row is expanded

### ISSUE THREAD

**Issue by vivekratnavel** [schrodinger/fixed-data-table-2#516]
## Expected Behavior
When a row is expanded and if the total height of rows + expanded row height exceeds the height of the table, then a vertical scrollbar should be available to scroll the expanded row content.

## Current Behavior
ScrollContentHeight of FixedDataTable2 does not get updated while expanding rows and hence there is no vertical scroll bar available to scroll while expanding last item in the table.

I have tried to capture this in a couple of recordings. Notice the state of FixedDataTable2 on the right side. Expanded row height in this example is 500 and normal row height is 70.

In the second gif, I tried to capture how the ScrollContentHeight value gets updated while the second row is also expanded.

![recording-1](https://user-images.githubusercontent.com/1051198/75632406-8f040b00-5bb0-11ea-82d1-9c30893be3f8.gif)

![recording-2](https://user-images.githubusercontent.com/1051198/75632455-0cc81680-5bb1-11ea-958d-0e1627b24013.gif)

## Possible Solution
Call updateRowHeight when a row is expanded.

## Steps to Reproduce (for bugs)

1. Populate the table with rows that do not exceed the table height
2. Set the expanded row height to be a higher value such that (number of rows * rowHeight + expanded row height) exceeds the table height

Then try to expand the last row in the table

## Context
This issue affects Omniboard users - https://github.com/vivekratnavel/omniboard/issues/48

This is reproduced even with [v1.0.2](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.2)

## Your Environment

* Version used: v1.0.2
* Browser Name and version: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac OS Mojave 10.14.5
* Link to your project: https://github.com/vivekratnavel/omniboard

**Comment by wcjordan** [comment]
Hey Vivek, thanks for filing this issue.  If you could create a small reproduction of the issue in a Codepen or similar tool, that would go a long way to determining what's going on.  It may be possible to use [this Codepen](https://codepen.io/alphalpha/pen/oqKJgG) as a starting point although I think that may be too far out of date.

One thing that jumps to my mind and is worth keeping in mind is that FDT2 doesn't have any direct notice about changes to which rows are expanded.  In our [Expanded Rows](https://github.com/schrodinger/fixed-data-table-2/blob/master/examples/ExpandedExample.js) we work around this by scrolling to a row whenever any row is expanded or collapsed.  Since that updates the table props and kicks off a scroll action, the scroll action recalculates the row heights for any rows in the viewport.  It may be worth walking through your use case with the debugger and confirm that a similar scroll action is occurring when you expand / collapse rows, and if not, perhaps add a prop change to trigger one.

Making a better API for informing FDT2 when rows expand / collapse would be nice.  If you'd like to file a linked enhancement for that we'd be happy to have one.  We also have a similar concern when it comes to knowing when the data in cells changes (discussed in #166 & #162).

**Comment by vivekratnavel** [comment]
Hi @wcjordan, thanks for your swift response. I am unable to reproduce this issue now. I may have experienced this due to some browser caching while upgrading FDT2 from v0.8 to v1.0.2. 

But, I created a codesandbox while trying to reproduce this issue and it will be helpful for others to fork it - https://codesandbox.io/s/react-playground-y6zof

**Comment by wcjordan** [comment]
Great, glad to hear it's working now.  And thank you for the codesandbox!  I'll add this to our issue to fix our issue template.  Thanks again.
