### ISSUE TITLE
scroll position is wrong when render a div before table

### ISSUE THREAD

**Issue by hung3102** [schrodinger/fixed-data-table-2#522]
## Expected Behavior

Y scroll position has to be correct.

## Current Behavior

I keep previous topPosition when the table rendered, then scrollTop to that topPosition.
But when I render `Loading` div before `statsus` is ready, the scroll position will be different as previous.

## Steps to Reproduce (for bugs)

CodePen: https://codesandbox.io/s/blissful-swanson-y15pb

## Your Environment

* Version used: 1.0.2
* Browser Name and version: Chrome  v.80
* Operating System and version (desktop or mobile): desktop window 10

**Comment by wcjordan** [comment]
Thanks for filing.  The reason you're seeing this issue is due to the fact that when you unmount the table it's destroying and creating a new table copy which clears the row height cache (doesn't have the row heights of the previous table).  This means any rows not in the viewport (or row buffer) are being reset to a height of 28.

To understand this a bit better, FDT uses the rowHeight prop (28 in the example) to give an initial height to each row.  When rows are within the viewport or buffer, their actual rowHeight is calculated using rowHeightGetter, but it would be problematic for performance if we did this for all the rows.  We keep the result of rowHeightGetter in a cache so that when you scroll rows which move offscreen don't revert to the rowHeight estimate. 
 When you unmount and remount, you're creating a new table, and it doesn't have the cache.  So all the rows off screen are getting reverted back to the rowHeight estimate.

To fix this I recommend hiding the table instead of unmounting it.  This will keep the cache around and resolve the issue.  In the longer term it may make sense to allow creating a redux store and passing it to the table rather than always creating a new one.  If you want to explore a PR which allows that we'd be happy to take a look.

Hopefully this helps.  Let me know if you have any issues.  I'm going to close for now, but please feel free to ask follow ups here.
