### ISSUE TITLE
Is it possible to hide an entire row by css?

### ISSUE THREAD

**Issue by MatteoGioioso** [schrodinger/fixed-data-table-2#524]
Hello

I would like to know if is is possible to hide an entire row or cell by css? 
I have tried by setting its height 0 or display hidden, but it did not work.
As I understood the `rowsCount` is interfering with the height.

Thanks

**Comment by wcjordan** [comment]
I don't think you'd want to hide by CSS since that would screw up the placement of all the other rows, just leaving a blank space.  I would recommend hiding the row by simply removing it from your data set.

I'm going to close this for now, but please feel free to comment here if you have any questions.

**Comment by MatteoGioioso** [comment]
Yes, thanks for the clarification. That's what I have ended up doing.
