### ISSUE TITLE
How to set option to close Infinite Scroll

### ISSUE THREAD

**Issue by WangYang-Rex** [schrodinger/fixed-data-table-2#552]
if there are many cols and rows,  table's performance is bad when it's scrolling , so i want to try without Infinite Scroll;
how to set option to close Infinite Scroll

**Comment by pradeepnschrodinger** [comment]
Sorry, not sure what you mean by "Infinite Scroll." 

FDT currently has performance problems rendering a large no:of columns because FDT doesn't virtualize them. 
You can use the column prop `allowCellsRecycling` to make sure only visible columns are rendered.

With that said, most of the times performance is a problem due to the cell renderers not being optimized. You can take a look at https://github.com/schrodinger/fixed-data-table-2/issues/146#issuecomment-293570322 and https://github.com/schrodinger/fixed-data-table-2/issues/190 to get more details.

**Comment by WangYang-Rex** [comment]
@pradeepnschrodinger 
Thanks, `allowCellsRecycling` works for me

**Comment by pradeepnschrodinger** [comment]
Glad to hear that. I'll close this issue, but feel free to continue the discussion here if you run into any related issues.
