### ISSUE TITLE
Using Webkit ScrollBar with fixed-data-table-2

### ISSUE THREAD

**Issue by xahitbayri** [schrodinger/fixed-data-table-2#558]
Hi,

I would like to use webkit-scrollbar component with fixed-data-table-2. How can I disable the "public_Scrollbar_main" and use the webkit-scrollbar element ?

Thank you,
Vahit.

**Comment by xahitbayri** [comment]
My main motivation for this is that I have customized the webkit-scrollbar according to my needs. I have changed the increment button image etc. 

Can I add increment/decrement button to "public_Scrollbar_main" element ?

**Comment by pradeepnschrodinger** [comment]
Unfortunately, FDT currently doesn't use/support native scrollbars. Instead we use a custom scrollbar component that's styled with CSS.
Hence, selectors like `::-webkit-scrollbar` probably won't work since there's no actual scrollbar in the table.

Instead, you could try passing your own custom react scrollbar component through the `scrollbarX` and `scrollbarY` table props.
More info can be found in #507 and #518, and you can refer to the [default scrollbar implementation here](https://github.com/schrodinger/fixed-data-table-2/blob/master/src/plugins/Scrollbar.js#L171). 

We don't have any examples yet. @rtrg, do you have any we could add to the site?

**Comment by wcjordan** [comment]
@xahitbayri I'm going to close as there's nothing more for us to do here, but please feel free to follow up here if you have any more questions with using your own scrollbar implementation w/ FDT.
