### ISSUE TITLE
I am using fixed-data-table-2 in my React Application, i would like to hide/remove the borders of the cells , could some help on how to do that

### ISSUE THREAD

**Issue by AdityaKallur** [schrodinger/fixed-data-table-2#594]

**Comment by pradeepnschrodinger** [comment]
The borders of the cell are styled through CSS by fixedDataTableCellLayout.css 
https://github.com/schrodinger/fixed-data-table-2/blob/1010d2688c943d75a937e6d4d5d8915e36932451/src/css/layout/fixedDataTableCellLayout.css#L12-L21

The class name specified here `fixedDataTableCellLayout/main` transforms into `fixedDataTableCellLayout_main`. So you should be able to simply disable the border style through something like:
```
.fixedDataTableCellLayout_main {
  border: none;
}
```

You can also refer the [style example](http://schrodinger.github.io/fixed-data-table-2/example-styling.html) to see how we can pass custom class names and/or styles to do the same.

I'll close of the issue since I believe the snippet above should do the trick, but feel free to continue the discussion.
