### ISSUE TITLE
Collapse row example missing collapsed rows

### ISSUE THREAD

**Issue by cajoy** [schrodinger/fixed-data-table-2#88]
I don't see any rows when click to expand collapsed row. Just height increased.

Can someone provide an example of it?

**Comment by wcjordan** [comment]
The collapsed rows example isn't meant to have nested rows or other content.  It just demonstrates that a rows behavior can be changed through clicking an icon or otherwise programatically.  

For what you're looking for you should consider forking and taking PR #73 or look at issue #79 
We don't plan to support this natively in FDT as we are unable to maintain it at this time.
