### ISSUE TITLE
Add ref="" to FixedDataTable component for the access to this component from parent

### ISSUE THREAD

**Issue by vladislavprokopenko** [schrodinger/fixed-data-table-2#96]
## Expected Behavior
It would be great to have access from parent component to the child component (FixedDataTable)

## Current Behavior
Now we only can get the access to the TransitionTable component, but no to the FixedDataTable

## Possible Solution
Add ref="" to the FixedDataTable

## Context
For example, we want to watch for state changes of FixedTableData from the parent component (e.g. "state.scrollY"). Now, we haven't the possibility for this.

## Your Environment
* Version used: 0.7.8
* Browser Name and version: Google Chrome 55.0.2883.75 
* Operating System and version (desktop or mobile): Ubuntu 16.04 desktop
* Link to your project:

**Comment by KamranAsif** [comment]
You can listen to scrolling state changes via [onScrollStart](http://schrodinger.github.io/fixed-data-table-2/api-table.html#-onscrollstart-) and [onScrollEnd](http://schrodinger.github.io/fixed-data-table-2/api-table.html#-onscrollend-)

With regards to accessing the component via ref, this is possible in FDT2 since we don't have a transition component anymore.

**Comment by KamranAsif** [comment]
Closing since there doesn't seem be an actual issue here.
